services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: advanced-reports
      POSTGRES_USER: advanced-reports
      POSTGRES_PASSWORD: advanced-reports
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
  redis_data: