spring.config.import=optional:classpath:application-secrets.properties
spring.docker.compose.file=backend/docker-compose.yaml
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-retries=3
spring.rabbitmq.listener.simple.retry.multiplier=2
spring.rabbitmq.listener.simple.retry.max-interval=10000
